/*
You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

Example 1:
Input: s = "abcd", t = "bdace"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:
Input: s = "", t = "y"
Output: "y"

Constraints:
0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.

  O(k);
  O(logn);
  O(n);
  O(n^2);
  
*/

var findTheDifference = function (s, t) {
	let map = {};

	for (let i = 0; i < s.length; i++) {
		if (map[s[i]] in map) {
			map[s[i]]++;
		} else {
			map[s[i]] = 1;
		}
	}

	for (let i = 0; i < t.length; i++) {
		if (!(t[i] in map) || map[t[i]] === 0) {
			return t[i];
		} else {
			map[t[i]]--;
		}
	}
};

// console.log(findTheDifference("abcd", "bdace"));

function testFindTheDifference() {
	let testArr = [
		["abcd", "bdace", "e"], //test1
		["", "y", "y"], //test2
		["a", "aa", "a"], //test3
	];

	for (const [string1, string2, ans] of testArr) {
		let hanksAns = findTheDifference(string1, string2);
		console.log(assert(hanksAns, ans));
	}
}

function assert(actual, expected) {
	if (actual === expected) {
		return "You got it!";
	} else {
		return "Why'd you fuck up, do better!";
	}
}

testFindTheDifference();

// var findTheDifference = function(s, t) {
//   /* put your answer in here
//   1. Iterate string s into a an array of individual indices
//   2. Iterate string t into a an array of individual indices
//   3. Compare each indices from string s and t to see if they equal
//   4. Continue this process until there is no match in string t.
//   5. Return the index of string t that does not match string s.
//   */
//   for (let i = 0; i < t.length; i++) {
//     let hasBeenFound = false;
//     for (let k = 0; k < s.length; k++) {
//       if ( s[k] == i) {
//         hasBeenFound = true;
//       }
//     }
//     if(!hasBeenFound) {
//       return t[i];
//     }
//   }
// }

// console.log(findTheDifference("a", "aa"));
